baseURL = "https://frankadrian.net/"
languageCode = "en-us"
title = "Frank Adrian"

theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "frankadrian-net"

# Google Analytics UA number
googleAnalytics = "UA-129031052-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."


# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Projects"
  weight = 15
  identifier = "project"
  url = "/project/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"


# Add your own params here
[params]
  author = "Frank Adrian"
  avatar = "/images/avatar.jpg"
  seotitle = "Frank Adrian"
  subtitle = "(Mostly) Fullstack WebDev from Hamburg, Germany"
  description = "This is my personal webspace. Have a look at the projects I am involved in and get in touch with me"
  paginate = 10
  customStyle = "styles/custom.scss"

  # Choose your social networks
  email = "fa@frankadrian.net"
  github = "frankadrian"
  instagram = "thinkwin_win"
  facebook = "myuniversum"

  twitter = "frank_adrian"
  linkedin = "frank-adrian-519b8333"

  #weibo = "weibo_username"
  #wechat= "/images/qrcode.jpg" # Replace with your wechat qrcode image
  # google = "googlplus_id_number"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  changyan = false
  changyanId = "cyt3toRiB"
  changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "nlH6yr9n7vIhdSD6cVxKD8BnxF-S5l7O8edNGLbNMm0"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  # msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
